export const goalsFvie = [{
    "id": 1,
    "endDate": "2023-3-34",
    "achieved": false,
    "active": true,
    "profile": 1,
    "workouts": [
        {
            "id": 1,
            "name": "Chest Blaster",
            "type": "Chest",
            "completed": true,
            "programs": [],
            "exercises": [
                {
                    "id": 3,
                    "name": "Bench Press",
                    "description": "A compound exercise that works the chest, shoulders, and triceps using a barbell.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 1,
                    "name": "Push-ups",
                    "description": "A classic bodyweight exercise that works the chest, shoulders, and triceps.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 3,
                    "name": "Bench Press",
                    "description": "A compound exercise that works the chest, shoulders, and triceps using a barbell.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 1,
                    "name": "Push-ups",
                    "description": "A classic bodyweight exercise that works the chest, shoulders, and triceps.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 48,
                    "name": "Bench Press",
                    "description": "A compound exercise that works the chest, shoulders, and triceps using a barbell.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 47,
                    "name": "Dumbbell Chest Fly",
                    "description": "An isolation exercise that targets the chest muscles using dumbbells.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 46,
                    "name": "Push-ups",
                    "description": "A classic bodyweight exercise that works the chest, shoulders, and triceps.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 2,
                    "name": "Dumbbell Chest Fly",
                    "description": "An isolation exercise that targets the chest muscles using dumbbells.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                }
            ],
            "experienceLevel": "Beginner"
        },
        {
            "id": 2,
            "name": "Chest Blaster",
            "type": "Chest",
            "completed": false,
            "programs": [],
            "exercises": [
                {
                    "id": 6,
                    "name": "Cable Fly",
                    "description": "An isolation exercise that targets the chest muscles using cable machines.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                },
                {
                    "id": 50,
                    "name": "Decline Bench Press",
                    "description": "A variation of the bench press that targets the lower chest muscles using a barbell.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                },
                {
                    "id": 4,
                    "name": "Incline Dumbbell Press",
                    "description": "A variation of the dumbbell press that targets the upper chest muscles.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                },
                {
                    "id": 51,
                    "name": "Cable Fly",
                    "description": "An isolation exercise that targets the chest muscles using cable machines.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                },
                {
                    "id": 5,
                    "name": "Decline Bench Press",
                    "description": "A variation of the bench press that targets the lower chest muscles using a barbell.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                },
                {
                    "id": 49,
                    "name": "Incline Dumbbell Press",
                    "description": "A variation of the dumbbell press that targets the upper chest muscles.",
                    "muscleGroup": "Chest",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                }
            ],
            "experienceLevel": "Intermediate"
        },
        {
            "id": 4,
            "name": "Back buster",
            "type": "Back",
            "completed": false,
            "programs": [],
            "exercises": [
                {
                    "id": 11,
                    "name": "Seated Cable Rows",
                    "description": "An isolation exercise that targets the mid-back muscles using a cable machine.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 12,
                    "name": "Reverse Fly",
                    "description": "An isolation exercise that targets the rear deltoids and upper back muscles using dumbbells.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 57,
                    "name": "Reverse Fly",
                    "description": "An isolation exercise that targets the rear deltoids and upper back muscles using dumbbells.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 56,
                    "name": "Seated Cable Rows",
                    "description": "An isolation exercise that targets the mid-back muscles using a cable machine.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 10,
                    "name": "Bent-Over Barbell Rows",
                    "description": "A compound exercise that targets the upper and lower back muscles using a barbell.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 55,
                    "name": "Bent-Over Barbell Rows",
                    "description": "A compound exercise that targets the upper and lower back muscles using a barbell.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                }
            ],
            "experienceLevel": "Intermediate"
        },
        {
            "id": 6,
            "name": "Back buster",
            "type": "Back",
            "completed": true,
            "programs": [],
            "exercises": [
                {
                    "id": 62,
                    "name": "Pull-Up (Weighted)",
                    "description": "A compound exercise that targets the upper back and biceps using a pull-up bar and added weight.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 4,
                    "completed": false,
                    "userExperience": "Expert"
                },
                {
                    "id": 18,
                    "name": "Barbell Row",
                    "description": "A compound exercise that targets the upper and mid-back muscles using a barbell.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 4,
                    "completed": false,
                    "userExperience": "Expert"
                },
                {
                    "id": 63,
                    "name": "Barbell Row",
                    "description": "A compound exercise that targets the upper and mid-back muscles using a barbell.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 4,
                    "completed": false,
                    "userExperience": "Expert"
                },
                {
                    "id": 16,
                    "name": "Deadlift",
                    "description": "A compound exercise that targets the entire back, hamstrings, and glutes using a barbell.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 6,
                    "sets": 4,
                    "completed": false,
                    "userExperience": "Expert"
                },
                {
                    "id": 61,
                    "name": "Deadlift",
                    "description": "A compound exercise that targets the entire back, hamstrings, and glutes using a barbell.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 6,
                    "sets": 4,
                    "completed": false,
                    "userExperience": "Expert"
                },
                {
                    "id": 17,
                    "name": "Pull-Up (Weighted)",
                    "description": "A compound exercise that targets the upper back and biceps using a pull-up bar and added weight.",
                    "muscleGroup": "Back",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 4,
                    "completed": false,
                    "userExperience": "Expert"
                }
            ],
            "experienceLevel": "Expert"
        },
        {
            "id": 7,
            "name": "Legs smasher",
            "type": "Legs",
            "completed": true,
            "programs": [],
            "exercises": [
                {
                    "id": 20,
                    "name": "Lunges",
                    "description": "An isolation exercise that targets the quads, hamstrings, and glutes using bodyweight or dumbbells.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 66,
                    "name": "Leg Press",
                    "description": "A compound exercise that targets the quads, hamstrings, and glutes using a leg press machine.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 64,
                    "name": "Squats",
                    "description": "A compound exercise that targets the quads, hamstrings, and glutes using a barbell.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 19,
                    "name": "Squats",
                    "description": "A compound exercise that targets the quads, hamstrings, and glutes using a barbell.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 21,
                    "name": "Leg Press",
                    "description": "A compound exercise that targets the quads, hamstrings, and glutes using a leg press machine.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 65,
                    "name": "Lunges",
                    "description": "An isolation exercise that targets the quads, hamstrings, and glutes using bodyweight or dumbbells.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                }
            ],
            "experienceLevel": "Beginner"
        },
        {
            "id": 8,
            "name": "Legs smasher",
            "type": "Legs",
            "completed": true,
            "programs": [],
            "exercises": [
                {
                    "id": 24,
                    "name": "Romanian Deadlifts",
                    "description": "An isolation exercise that targets the hamstrings and glutes using a barbell or dumbbells.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                },
                {
                    "id": 19,
                    "name": "Squats",
                    "description": "A compound exercise that targets the quads, hamstrings, and glutes using a barbell.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 19,
                    "name": "Squats",
                    "description": "A compound exercise that targets the quads, hamstrings, and glutes using a barbell.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 19,
                    "name": "Squats",
                    "description": "A compound exercise that targets the quads, hamstrings, and glutes using a barbell.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 19,
                    "name": "Squats",
                    "description": "A compound exercise that targets the quads, hamstrings, and glutes using a barbell.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 67,
                    "name": "Deadlifts",
                    "description": "A compound exercise that targets the hamstrings, glutes, and lower back using a barbell.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                },
                {
                    "id": 23,
                    "name": "Barbell Squats",
                    "description": "A compound exercise that targets the quads, hamstrings, and glutes using a barbell.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                },
                {
                    "id": 22,
                    "name": "Deadlifts",
                    "description": "A compound exercise that targets the hamstrings, glutes, and lower back using a barbell.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                },
                {
                    "id": 68,
                    "name": "Barbell Squats",
                    "description": "A compound exercise that targets the quads, hamstrings, and glutes using a barbell.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 8,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                },
                {
                    "id": 69,
                    "name": "Romanian Deadlifts",
                    "description": "An isolation exercise that targets the hamstrings and glutes using a barbell or dumbbells.",
                    "muscleGroup": "Legs",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Intermediate"
                }
            ],
            "experienceLevel": "Intermediate"
        },
        {
            "id": 10,
            "name": "Boulder Shoulders",
            "type": "Shoulders",
            "completed": true,
            "programs": [],
            "exercises": [
                {
                    "id": 30,
                    "name": "Front Raises",
                    "description": "An isolation exercise that targets the front deltoids using dumbbells.",
                    "muscleGroup": "Shoulders",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 28,
                    "name": "Dumbbell Shoulder Press",
                    "description": "A compound exercise that targets the shoulders using dumbbells.",
                    "muscleGroup": "Shoulders",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 75,
                    "name": "Front Raises",
                    "description": "An isolation exercise that targets the front deltoids using dumbbells.",
                    "muscleGroup": "Shoulders",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 29,
                    "name": "Lateral Raises",
                    "description": "An isolation exercise that targets the lateral (side) deltoids using dumbbells.",
                    "muscleGroup": "Shoulders",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 73,
                    "name": "Dumbbell Shoulder Press",
                    "description": "A compound exercise that targets the shoulders using dumbbells.",
                    "muscleGroup": "Shoulders",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 10,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                },
                {
                    "id": 74,
                    "name": "Lateral Raises",
                    "description": "An isolation exercise that targets the lateral (side) deltoids using dumbbells.",
                    "muscleGroup": "Shoulders",
                    "exerciseImageLink": null,
                    "videoLink": null,
                    "reps": 12,
                    "sets": 3,
                    "completed": false,
                    "userExperience": "Beginner"
                }
            ],
            "experienceLevel": "Beginner"
        }
    ],
}
]